version: '3.7'

services:
  simmodel_app:
    container_name: simmodel_app
    restart: always
    build: ./simmodel_app
    command: gunicorn -w 1 -b :8000 app:server
    volumes:
      - ./simmodel_app/:/home/ubuntu/simmodel_app/
    ports:
      - "8000:8000"

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - simmodel_app
